config/routes.rb
SampleApp::Application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :microposts, only: [:create, :destroy]
    resource  :session,    only: [:new, :create, :destroy]

    get    'signup',  to: 'users#new'
    get    'signin',  to: 'sessions#new'
    delete 'signout', to: 'sessions#destroy'

    get 'help',    to: 'static_pages#help'
    get 'about',   to: 'static_pages#about'
    get 'contact', to: 'static_pages#contact'

    # handles /en|it|ja
    root to: 'static_pages#home', as: "locale_root"
    # handles /en|it|ja/fake-path
    get '*path', to: redirect { |params, request| "/#{params[:locale]}" }
  end

  resources :relationships, only: [:create, :destroy]

  # handles /
  root to: redirect("/#{I18n.default_locale}")
  # handles /bad-locale|anything/valid-path
  get '/*locale/*path', to: redirect("/#{I18n.default_locale}/%{path}")
  # handles /anything|valid-path-but-no-locale
  get '/*path', to: redirect("/#{I18n.default_locale}/%{path}")

end
#== Route Map
# Generated on 29 Jan 2013 23:30
#
# followers_user GET    /:locale/users/:id/followers(.:format) users#followers {:locale=>/en|it|ja/}
#          users GET    /:locale/users(.:format)               users#index {:locale=>/en|it|ja/}
#                POST   /:locale/users(.:format)               users#create {:locale=>/en|it|ja/}
#       new_user GET    /:locale/users/new(.:format)           users#new {:locale=>/en|it|ja/}
#      edit_user GET    /:locale/users/:id/edit(.:format)      users#edit {:locale=>/en|it|ja/}
#           user GET    /:locale/users/:id(.:format)           users#show {:locale=>/en|it|ja/}
#                PUT    /:locale/users/:id(.:format)           users#update {:locale=>/en|it|ja/}
#                DELETE /:locale/users/:id(.:format)           users#destroy {:locale=>/en|it|ja/}
#        session POST   /:locale/session(.:format)             sessions#create {:locale=>/en|it|ja/}
#    new_session GET    /:locale/session/new(.:format)         sessions#new {:locale=>/en|it|ja/}
#                DELETE /:locale/session(.:format)             sessions#destroy {:locale=>/en|it|ja/}
#     microposts POST   /:locale/microposts(.:format)          microposts#create {:locale=>/en|it|ja/}
#      micropost DELETE /:locale/microposts/:id(.:format)      microposts#destroy {:locale=>/en|it|ja/}
#         signup GET    /:locale/signup(.:format)              users#new {:locale=>/en|it|ja/}
#         signin GET    /:locale/signin(.:format)              sessions#new {:locale=>/en|it|ja/}
#        signout DELETE /:locale/signout(.:format)             sessions#destroy {:locale=>/en|it|ja/}
#           help GET    /:locale/help(.:format)                static_pages#help {:locale=>/en|it|ja/}
#          about GET    /:locale/about(.:format)               static_pages#about {:locale=>/en|it|ja/}
#        contact GET    /:locale/contact(.:format)             static_pages#contact {:locale=>/en|it|ja/}
#    locale_root        /:locale(.:format)                     static_pages#home {:locale=>/en|it|ja/}
#                GET    /:locale/*path(.:format)               :controller#:action {:locale=>/en|it|ja/}
#  relationships POST   /relationships(.:format)               relationships#create
#   relationship DELETE /relationships/:id(.:format)           relationships#destroy
#           root        /                                      :controller#:action
#                GET    /*locale/*path(.:format)               :controller#:action
#                GET    /*path(.:format)                       :controller#:action

app/views/layouts/_account_dropdown.html.haml
%li#fat-menu.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
    %i.icon-briefcase
    = t('.account')
    %b.caret
  %ul.dropdown-menu
    %li
      = link_to current_user do
        %i.icon-edit
        = t('.profile')
    %li
      = link_to edit_user_path(current_user) do
        %i.icon-cogs
        = t('.settings')
    %li.divider
    %li
      = link_to signout_path, method: :delete do
        %i.icon-signout
        = t('.sign_out')

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    = link_to t('.rails_tutorial'), "http://railstutorial.org"
    = t('.author')
  %nav
    %ul
      %li= link_to t('.about'),   about_path
      %li= link_to t('.contact'), contact_path
      %li= link_to t('.news'),    "http://news.railstutorial.org/"

app/views/layouts/_github_ribbon.html.haml
.github_ribbon
  = link_to image_tag("https://s3.amazonaws.com/github/ribbons/forkme_left_red_aa0000.png"),
      "https://github.com/paulfioravanti/sample_app", alt: "Fork me on GitHub"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to t('.sample_app'), locale_root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li
            = link_to locale_root_path do
              %i.icon-home
              = t('.home')
          %li
            = link_to help_path do
              %i.icon-question-sign
              = t('.help')
          - if signed_in?
            %li
              = link_to users_path do
                %i.icon-user
                = t('.users')
            = render 'layouts/account_dropdown'
          - else
            %li
              = link_to signin_path do
                %i.icon-signin
                = t('.sign_in')
          = render 'layouts/locale_selector',
                    controller: controller,
                    action: action,
                    page: page

app/views/layouts/_i18n_js.html.haml
:javascript
  I18n.locale = "#{I18n.locale}";

app/views/layouts/_locale_selector.html.haml
%li#fat-menu.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
    %i.icon-globe
    = t('.language')
    %b.caret
  %ul.dropdown-menu
    - t('.language_labels').each_pair do |locale, label|
      %li
        = link_to label,
                  controller: controller,
                  action: action,
                  set_locale: locale,
                  page: page

app/views/layouts/_messages.html.haml
- flash.each do |name, message|
  %div{ class: "alert alert-#{name}" }
    %a.close{ "data-dismiss" => "alert" } ×
    = content_tag(:div, message, id: "flash_#{name}")

app/views/layouts/_shim.html.haml
/ [if lt IE 9]
  %script(src="http://html5shim.googlecode.com/svn/trunk/html15.js")

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = timeago_script_tag
    = csrf_meta_tags
    = render 'layouts/shim'
    = render 'layouts/i18n_js'
  %body{ class: "#{controller_name}-controller #{action_name}-action" }
    = render 'layouts/header',
             controller: @redirect_controller,
             action: @redirect_action,
             page: @page_number
    .container
      = render 'layouts/messages'
      = yield
      = render 'layouts/footer'